# Generated by Django 3.2.12 on 2022-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220413_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(max_length=191),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=191),
        ),
    ]
