# Generated by Django 3.2.12 on 2022-04-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220416_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=291),
            preserve_default=False,
        ),
    ]
