# Generated by Django 3.2.12 on 2022-04-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=265)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=180)),
                ('content', models.TextField()),
            ],
        ),
    ]
