# Generated by Django 3.2.12 on 2022-04-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
